[INFO][0][<module>] Linux dec1438 5.14.21-150400.24.46_12.0.73-cray_shasta_c #1 SMP Thu May 18 23:03:34 UTC 2023 (9c4698c) x86_64 x86_64
[INFO][0][<module>] /glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB (2.7)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/numpy (1.23.5)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/matplotlib (3.6.3)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/netCDF4 (1.6.2)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/cf_units (3.1.1)
[INFO][0][<module>] /glade/u/home/rfisher/.local/lib/python3.9/site-packages/sympy (1.12)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/mpi4py (3.1.4)
[INFO][0][<module>] 2023-09-15 06:43:18.894611
[DEBUG][4][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_FRACTION] in the model results
[DEBUG][4][WorkConfront][EcosystemRespiration/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][11][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_AUTORESP] in the model results
[DEBUG][11][WorkConfront][EcosystemRespiration/FLUXCOM][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

